import { v4 as uuidv4 } from "uuid";

const upgrades = [
  {
    id: uuidv4(),
    name: "Paper 🧻",
    price: 15000,
    pointsPerSeconds: 100,
    purchased: false,
    srcImage: "/img/upg/paper.png",
  },
  {
    id: uuidv4(),
    name: "Paper with poo 💩",
    price: 50000,
    pointsPerSeconds: 200,
    purchased: false,
    srcImage: "/img/upg/paper_poo.png",
  },
  {
    id: uuidv4(),
    name: "Europaper 💶",
    price: 500000,
    pointsPerSeconds: 500,
    purchased: false,
    srcImage: "/img/upg/euro_paper.png",
  },
  {
    id: uuidv4(),
    name: "Paper axe 🪓",
    price: 500000,
    pointsPerSeconds: 500,
    purchased: false,
    srcImage: "/img/upg/paper_axe.png",
  },
  {
    id: uuidv4(),
    name: "Stinky axe 🤢",
    price: 500000,
    pointsPerSeconds: 500,
    purchased: false,
    srcImage: "/img/upg/stinky_axe.png",
  },
  {
    id: uuidv4(),
    name: "Euroaxe 💶",
    price: 500000,
    pointsPerSeconds: 500,
    purchased: false,
    srcImage: "/img/upg/euro_axe.png",
  },
  {
    id: uuidv4(),
    name: "Bag of paper 💰",
    price: 500000,
    pointsPerSeconds: 500,
    purchased: false,
    srcImage: "/img/upg/bag_paper.png",
  },
  {
    id: uuidv4(),
    name: "Suspicious bag 🤨",
    price: 500000,
    pointsPerSeconds: 500,
    purchased: false,
    srcImage: "/img/upg/suspicious_bag.png",
  },
  {
    id: uuidv4(),
    name: "THE BAG 👑",
    price: 500000,
    pointsPerSeconds: 500,
    purchased: false,
    srcImage: "/img/upg/the_bag.png",
  },
  {
    id: uuidv4(),
    name: "A normal rocket 🚀",
    price: 500000,
    pointsPerSeconds: 500,
    purchased: false,
    srcImage: "/img/upg/rocket_paper.png",
  },
  {
    id: uuidv4(),
    name: "A rocket with... is that poo? 🟤",
    price: 500000,
    pointsPerSeconds: 500,
    purchased: false,
    srcImage: "/img/upg/rocket_poo.png",
  },
  {
    id: uuidv4(),
    name: "Pedro Sánchez's Rocket 🏆",
    price: 500000,
    pointsPerSeconds: 500,
    purchased: false,
    srcImage: "/img/upg/pedrocket.png",
  },
];

export default upgrades;
